# Generated by Django 5.2.14 on 2026-06-03 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_playlistimport_playlist'),
        ('rooms', '0002_remove_queueitem_rooms_queue_room_id_b4e783_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='queueitem',
            name='rooms_queue_room_id_d561cc_idx',
        ),
        migrations.RemoveField(
            model_name='playbackstate',
            name='context_label',
        ),
        migrations.RemoveField(
            model_name='playbackstate',
            name='current_track',
        ),
        migrations.RemoveField(
            model_name='queueitem',
            name='kind',
        ),
        migrations.AddField(
            model_name='playbackstate',
            name='current_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rooms.queueitem'),
        ),
        migrations.AddIndex(
            model_name='queueitem',
            index=models.Index(fields=['room', 'position'], name='rooms_queue_room_id_b4e783_idx'),
        ),
    ]
