# Generated by Django 5.2.14 on 2026-06-03 03:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_playlistimport_playlist'),
        ('rooms', '0003_remove_queueitem_rooms_queue_room_id_d561cc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='queueitem',
            name='rooms_queue_room_id_b4e783_idx',
        ),
        migrations.AddField(
            model_name='playbackstate',
            name='context_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='playbackstate',
            name='context_pos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queueitem',
            name='kind',
            field=models.CharField(choices=[('context', 'From context'), ('queue', 'User queue')], default='context', max_length=8),
        ),
        migrations.AddIndex(
            model_name='queueitem',
            index=models.Index(fields=['room', 'kind', 'position'], name='rooms_queue_room_id_d561cc_idx'),
        ),
    ]
