# Generated by Django 5.2.15 on 2026-06-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_roommember_playbackstate_generation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbackstate',
            name='pending_start',
            field=models.BooleanField(default=False),
        ),
    ]
