# Generated by Django 5.2.15 on 2026-06-06 03:25

import apps.rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_playbackstate_pending_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbackstate',
            name='next_shuffle_seed',
            field=models.BigIntegerField(default=apps.rooms.models._new_shuffle_seed),
        ),
    ]
