# Generated by Django 5.2.15 on 2026-06-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_playbackstate_next_shuffle_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbackstate',
            name='start_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
