/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List + retrieve workflow runs the current user has triggered. */
        get: operations["v1_jobs_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List + retrieve workflow runs the current user has triggered. */
        get: operations["v1_jobs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/trigger/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description List + retrieve workflow runs the current user has triggered. */
        post: operations["v1_jobs_trigger_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description CRUD viewset for Notes.
         *
         *     Notably, `get_queryset` returns `Note.objects.all()` with **no**
         *     `.filter(owner=self.request.user)`. RLS policies enforce per-user
         *     isolation at the database. Tests in `tests/test_rls.py` prove that
         *     forgetting the app-layer filter does not leak rows.
         */
        get: operations["v1_notes_list"];
        put?: never;
        /**
         * @description CRUD viewset for Notes.
         *
         *     Notably, `get_queryset` returns `Note.objects.all()` with **no**
         *     `.filter(owner=self.request.user)`. RLS policies enforce per-user
         *     isolation at the database. Tests in `tests/test_rls.py` prove that
         *     forgetting the app-layer filter does not leak rows.
         */
        post: operations["v1_notes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description CRUD viewset for Notes.
         *
         *     Notably, `get_queryset` returns `Note.objects.all()` with **no**
         *     `.filter(owner=self.request.user)`. RLS policies enforce per-user
         *     isolation at the database. Tests in `tests/test_rls.py` prove that
         *     forgetting the app-layer filter does not leak rows.
         */
        get: operations["v1_notes_retrieve"];
        /**
         * @description CRUD viewset for Notes.
         *
         *     Notably, `get_queryset` returns `Note.objects.all()` with **no**
         *     `.filter(owner=self.request.user)`. RLS policies enforce per-user
         *     isolation at the database. Tests in `tests/test_rls.py` prove that
         *     forgetting the app-layer filter does not leak rows.
         */
        put: operations["v1_notes_update"];
        post?: never;
        /**
         * @description CRUD viewset for Notes.
         *
         *     Notably, `get_queryset` returns `Note.objects.all()` with **no**
         *     `.filter(owner=self.request.user)`. RLS policies enforce per-user
         *     isolation at the database. Tests in `tests/test_rls.py` prove that
         *     forgetting the app-layer filter does not leak rows.
         */
        delete: operations["v1_notes_destroy"];
        options?: never;
        head?: never;
        /**
         * @description CRUD viewset for Notes.
         *
         *     Notably, `get_queryset` returns `Note.objects.all()` with **no**
         *     `.filter(owner=self.request.user)`. RLS policies enforce per-user
         *     isolation at the database. Tests in `tests/test_rls.py` prove that
         *     forgetting the app-layer filter does not leak rows.
         */
        patch: operations["v1_notes_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Note: {
            readonly id: number;
            title: string;
            body?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        PaginatedNoteList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Note"][];
        };
        PaginatedWorkflowRunList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["WorkflowRun"][];
        };
        PatchedNote: {
            readonly id?: number;
            title?: string;
            body?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /**
         * @description * `PENDING` - Pending
         *     * `RUNNING` - Running
         *     * `SUCCEEDED` - Succeeded
         *     * `FAILED` - Failed
         *     * `CANCELLED` - Cancelled
         * @enum {string}
         */
        StatusEnum: "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
        WorkflowRun: {
            readonly id: number;
            /** @description Hatchet workflow class name */
            workflow: string;
            readonly hatchet_run_id: string;
            input?: unknown;
            readonly status: components["schemas"]["StatusEnum"];
            readonly error: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_jobs_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedWorkflowRunList"];
                };
            };
        };
    };
    v1_jobs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this workflow run. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRun"];
                };
            };
        };
    };
    v1_jobs_trigger_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowRun"];
                "application/x-www-form-urlencoded": components["schemas"]["WorkflowRun"];
                "multipart/form-data": components["schemas"]["WorkflowRun"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRun"];
                };
            };
        };
    };
    v1_notes_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNoteList"];
                };
            };
        };
    };
    v1_notes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Note"];
                "application/x-www-form-urlencoded": components["schemas"]["Note"];
                "multipart/form-data": components["schemas"]["Note"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
        };
    };
    v1_notes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this note. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
        };
    };
    v1_notes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this note. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Note"];
                "application/x-www-form-urlencoded": components["schemas"]["Note"];
                "multipart/form-data": components["schemas"]["Note"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
        };
    };
    v1_notes_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this note. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_notes_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this note. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedNote"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedNote"];
                "multipart/form-data": components["schemas"]["PatchedNote"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
        };
    };
}
