/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/catalog/ingest/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Paste a source URL → loose catalog Tracks (no playlist created).
         *
         *     The client then chooses what to do with them: play, add to queue, or save
         *     as a playlist (all handled by the rooms API).
         */
        post: operations["v1_catalog_ingest_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/playlists/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List/retrieve owned playlists (created via save-as-playlist). */
        get: operations["v1_catalog_playlists_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/playlists/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List/retrieve owned playlists (created via save-as-playlist). */
        get: operations["v1_catalog_playlists_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/tracks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve tracks; list candidates; correct the active playback source. */
        get: operations["v1_catalog_tracks_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/tracks/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve tracks; list candidates; correct the active playback source. */
        get: operations["v1_catalog_tracks_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/tracks/{id}/candidates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve tracks; list candidates; correct the active playback source. */
        get: operations["v1_catalog_tracks_candidates_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/tracks/{id}/match/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Resolve this track's YouTube source on demand (lazy — used by Play).
         *
         *     Returns the existing active source if already matched (no wasted
         *     YouTube search); otherwise resolves one; 404 if nothing fits.
         */
        post: operations["v1_catalog_tracks_match_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/tracks/{id}/set-source/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Retrieve tracks; list candidates; correct the active playback source. */
        post: operations["v1_catalog_tracks_set_source_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description CRUD viewset for Notes.
         *
         *     Notably, `get_queryset` returns `Note.objects.all()` with **no**
         *     `.filter(owner=self.request.user)`. RLS policies enforce per-user
         *     isolation at the database. Tests in `tests/test_rls.py` prove that
         *     forgetting the app-layer filter does not leak rows.
         */
        get: operations["v1_notes_list"];
        put?: never;
        /**
         * @description CRUD viewset for Notes.
         *
         *     Notably, `get_queryset` returns `Note.objects.all()` with **no**
         *     `.filter(owner=self.request.user)`. RLS policies enforce per-user
         *     isolation at the database. Tests in `tests/test_rls.py` prove that
         *     forgetting the app-layer filter does not leak rows.
         */
        post: operations["v1_notes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description CRUD viewset for Notes.
         *
         *     Notably, `get_queryset` returns `Note.objects.all()` with **no**
         *     `.filter(owner=self.request.user)`. RLS policies enforce per-user
         *     isolation at the database. Tests in `tests/test_rls.py` prove that
         *     forgetting the app-layer filter does not leak rows.
         */
        get: operations["v1_notes_retrieve"];
        /**
         * @description CRUD viewset for Notes.
         *
         *     Notably, `get_queryset` returns `Note.objects.all()` with **no**
         *     `.filter(owner=self.request.user)`. RLS policies enforce per-user
         *     isolation at the database. Tests in `tests/test_rls.py` prove that
         *     forgetting the app-layer filter does not leak rows.
         */
        put: operations["v1_notes_update"];
        post?: never;
        /**
         * @description CRUD viewset for Notes.
         *
         *     Notably, `get_queryset` returns `Note.objects.all()` with **no**
         *     `.filter(owner=self.request.user)`. RLS policies enforce per-user
         *     isolation at the database. Tests in `tests/test_rls.py` prove that
         *     forgetting the app-layer filter does not leak rows.
         */
        delete: operations["v1_notes_destroy"];
        options?: never;
        head?: never;
        /**
         * @description CRUD viewset for Notes.
         *
         *     Notably, `get_queryset` returns `Note.objects.all()` with **no**
         *     `.filter(owner=self.request.user)`. RLS policies enforce per-user
         *     isolation at the database. Tests in `tests/test_rls.py` prove that
         *     forgetting the app-layer filter does not leak rows.
         */
        patch: operations["v1_notes_partial_update"];
        trace?: never;
    };
    "/api/v1/rooms/clear/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description The caller's own listening room (room-of-one). All actions operate on
         *     `request.user`'s active room — there is no other-user access.
         */
        post: operations["v1_rooms_clear_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/jump/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Play a specific queue item now (click any row in the queue). */
        post: operations["v1_rooms_jump_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The caller's own listening room (room-of-one). All actions operate on
         *     `request.user`'s active room — there is no other-user access.
         */
        get: operations["v1_rooms_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/next/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description The caller's own listening room (room-of-one). All actions operate on
         *     `request.user`'s active room — there is no other-user access.
         */
        post: operations["v1_rooms_next_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/play/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Replace the queue with a list and play from `start_index`
         *     (Play playlist / Play all).
         */
        post: operations["v1_rooms_play_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/play-now/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Play one song now (clicking a track) — inserts it at the cursor; does
         *     not pull in the surrounding list.
         */
        post: operations["v1_rooms_play_now_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/play-playlist/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description The caller's own listening room (room-of-one). All actions operate on
         *     `request.user`'s active room — there is no other-user access.
         */
        post: operations["v1_rooms_play_playlist_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/previous/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description The caller's own listening room (room-of-one). All actions operate on
         *     `request.user`'s active room — there is no other-user access.
         */
        post: operations["v1_rooms_previous_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/queue/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Add one or more tracks to the queue (`play_next` → right after current). */
        post: operations["v1_rooms_queue_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/remove/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Remove a single queue item. */
        post: operations["v1_rooms_remove_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/save-as-playlist/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description The caller's own listening room (room-of-one). All actions operate on
         *     `request.user`'s active room — there is no other-user access.
         */
        post: operations["v1_rooms_save_as_playlist_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/shuffle/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Reshuffle the up-next items. */
        post: operations["v1_rooms_shuffle_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/passkey-credential-ids/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_users_passkey_credential_ids_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The result of a paste: loose tracks the caller can play/queue/save. */
        ImportResult: {
            /** Format: uuid */
            readonly id: string;
            readonly title: string;
            readonly track_count: number;
            readonly tracks: components["schemas"]["Track"][];
        };
        Ingest: {
            /** Format: uri */
            url: string;
        };
        /**
         * @description * `video_id` - YouTube video id
         *     * `storage_key` - Object-storage key
         *     * `url` - Direct URL
         * @enum {string}
         */
        LocatorKindEnum: "video_id" | "storage_key" | "url";
        Note: {
            readonly id: number;
            title: string;
            body?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `matched_auto` - Matched (auto)
         *     * `matched_manual` - Matched (manual correction)
         *     * `direct` - Direct (paste/upload, no search)
         * @enum {string}
         */
        OriginEnum: "matched_auto" | "matched_manual" | "direct";
        PaginatedNoteList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Note"][];
        };
        PaginatedPlaybackSourceList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["PlaybackSource"][];
        };
        PaginatedPlaylistList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Playlist"][];
        };
        PaginatedTrackList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Track"][];
        };
        PatchedNote: {
            readonly id?: number;
            title?: string;
            body?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /** @description Replace the queue with `track_ids` and play from `start_index`. */
        Play: {
            track_ids: string[];
            /** @default 0 */
            start_index: number;
        };
        /** @description Play a single track now (insert at the cursor). */
        PlayNow: {
            /** Format: uuid */
            track_id: string;
        };
        PlayPlaylist: {
            /** Format: uuid */
            playlist_id: string;
        };
        PlaybackSource: {
            /** Format: uuid */
            readonly id: string;
            readonly source_code: string;
            locator_kind: components["schemas"]["LocatorKindEnum"];
            locator: string;
            status?: components["schemas"]["StatusEnum"];
            origin: components["schemas"]["OriginEnum"];
            /** Format: double */
            confidence?: number | null;
            duration_delta_ms?: number | null;
            title?: string;
            uploader?: string;
            duration_ms?: number | null;
        };
        Playlist: {
            /** Format: uuid */
            readonly id: string;
            title: string;
            is_public?: boolean;
            readonly track_count: number;
            /** Format: date-time */
            readonly created_at: string;
        };
        PlaylistDetail: {
            /** Format: uuid */
            readonly id: string;
            title: string;
            description?: string;
            is_public?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            readonly track_count: number;
            readonly items: components["schemas"]["PlaylistTrack"][];
        };
        PlaylistTrack: {
            position: number;
            readonly track: components["schemas"]["Track"];
        };
        /** @description Add tracks to the queue. `play_next` inserts right after current. */
        Queue: {
            track_ids: string[];
            /** @default false */
            play_next: boolean;
        };
        QueueItem: {
            /** Format: uuid */
            readonly id: string;
            position: number;
            readonly track: components["schemas"]["Track"];
        };
        /** @description Reference an existing queue item (for jump / remove). */
        QueueItemRef: {
            /** Format: uuid */
            item_id: string;
        };
        /**
         * @description The room as the player needs it: now-playing + the single queue split into
         *     already-played `history` and upcoming `queue`, around the current cursor.
         */
        Room: {
            /** Format: uuid */
            readonly id: string;
            readonly current: components["schemas"]["Track"];
            /** Format: uuid */
            readonly current_item_id: string | null;
            readonly is_playing: boolean;
            readonly position_ms: number;
            readonly history: components["schemas"]["QueueItem"][];
            readonly queue: components["schemas"]["QueueItem"][];
        };
        SaveAsPlaylist: {
            title: string;
        };
        /**
         * @description Correct a track's playback source: paste a YouTube video id OR promote
         *     an existing candidate by its PlaybackSource id.
         */
        SetSource: {
            video_id?: string;
            /** Format: uuid */
            playback_source_id?: string;
        };
        /**
         * @description * `active` - Active
         *     * `candidate` - Candidate
         *     * `dead` - Dead
         *     * `replaced` - Replaced
         *     * `rejected` - Rejected
         * @enum {string}
         */
        StatusEnum: "active" | "candidate" | "dead" | "replaced" | "rejected";
        Track: {
            /** Format: uuid */
            readonly id: string;
            title: string;
            primary_artist: string;
            duration_ms?: number | null;
            isrc?: string;
            readonly active_source: components["schemas"]["PlaybackSource"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_catalog_ingest_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Ingest"];
                "application/x-www-form-urlencoded": components["schemas"]["Ingest"];
                "multipart/form-data": components["schemas"]["Ingest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
        };
    };
    v1_catalog_playlists_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPlaylistList"];
                };
            };
        };
    };
    v1_catalog_playlists_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this playlist. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetail"];
                };
            };
        };
    };
    v1_catalog_tracks_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTrackList"];
                };
            };
        };
    };
    v1_catalog_tracks_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this track. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Track"];
                };
            };
        };
    };
    v1_catalog_tracks_candidates_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description A UUID string identifying this track. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPlaybackSourceList"];
                };
            };
        };
    };
    v1_catalog_tracks_match_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this track. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybackSource"];
                };
            };
        };
    };
    v1_catalog_tracks_set_source_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this track. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SetSource"];
                "application/x-www-form-urlencoded": components["schemas"]["SetSource"];
                "multipart/form-data": components["schemas"]["SetSource"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybackSource"];
                };
            };
        };
    };
    v1_notes_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNoteList"];
                };
            };
        };
    };
    v1_notes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Note"];
                "application/x-www-form-urlencoded": components["schemas"]["Note"];
                "multipart/form-data": components["schemas"]["Note"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
        };
    };
    v1_notes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this note. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
        };
    };
    v1_notes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this note. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Note"];
                "application/x-www-form-urlencoded": components["schemas"]["Note"];
                "multipart/form-data": components["schemas"]["Note"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
        };
    };
    v1_notes_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this note. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_notes_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this note. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedNote"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedNote"];
                "multipart/form-data": components["schemas"]["PatchedNote"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
        };
    };
    v1_rooms_clear_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
        };
    };
    v1_rooms_jump_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueueItemRef"];
                "application/x-www-form-urlencoded": components["schemas"]["QueueItemRef"];
                "multipart/form-data": components["schemas"]["QueueItemRef"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
        };
    };
    v1_rooms_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
        };
    };
    v1_rooms_next_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
        };
    };
    v1_rooms_play_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Play"];
                "application/x-www-form-urlencoded": components["schemas"]["Play"];
                "multipart/form-data": components["schemas"]["Play"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
        };
    };
    v1_rooms_play_now_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayNow"];
                "application/x-www-form-urlencoded": components["schemas"]["PlayNow"];
                "multipart/form-data": components["schemas"]["PlayNow"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
        };
    };
    v1_rooms_play_playlist_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayPlaylist"];
                "application/x-www-form-urlencoded": components["schemas"]["PlayPlaylist"];
                "multipart/form-data": components["schemas"]["PlayPlaylist"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
        };
    };
    v1_rooms_previous_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
        };
    };
    v1_rooms_queue_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Queue"];
                "application/x-www-form-urlencoded": components["schemas"]["Queue"];
                "multipart/form-data": components["schemas"]["Queue"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
        };
    };
    v1_rooms_remove_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueueItemRef"];
                "application/x-www-form-urlencoded": components["schemas"]["QueueItemRef"];
                "multipart/form-data": components["schemas"]["QueueItemRef"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
        };
    };
    v1_rooms_save_as_playlist_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveAsPlaylist"];
                "application/x-www-form-urlencoded": components["schemas"]["SaveAsPlaylist"];
                "multipart/form-data": components["schemas"]["SaveAsPlaylist"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Playlist"];
                };
            };
        };
    };
    v1_rooms_shuffle_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
        };
    };
    v1_users_passkey_credential_ids_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
