# Generated by Django 5.2.15 on 2026-06-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('jam_join', 'Joined your jam'), ('friend_request', 'Sent you a friend request'), ('friend_accept', 'Accepted your friend request')], max_length=32),
        ),
    ]
