# Generated by Django 5.2.15 on 2026-06-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('jam_join', 'Joined your jam'), ('friend_request', 'Sent you a friend request'), ('friend_accept', 'Accepted your friend request'), ('playlist_invite', 'Invited you to collaborate'), ('playlist_invite_accept', 'Joined your playlist'), ('playlist_tracks', 'Updated a shared playlist')], max_length=32),
        ),
    ]
