# Generated by Django 5.2.15 on 2026-06-05 03:45

import secrets

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _invite_token() -> str:
    # Local to this migration: the raw-token default Invitation originally shipped with.
    # Migration 0003 hashes then drops this column, so the live model no longer defines
    # this function — kept here only so this historical migration imports standalone.
    return secrets.token_urlsafe(32)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('token', models.CharField(default=_invite_token, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=apps.users.models._invite_expiry)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
