# Generated by Django 5.2.14 on 2026-06-02 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('catalog', 'Catalog (ingest tracks from)'), ('playback', 'Playback (stream audio from)'), ('both', 'Both')], max_length=16)),
                ('ingest_method', models.CharField(choices=[('api', 'API'), ('scrape', 'Scrape'), ('yt_dlp', 'yt-dlp'), ('upload', 'Upload'), ('none', 'None')], max_length=16)),
                ('url_patterns', models.JSONField(blank=True, default=list)),
                ('base_url', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isrc', models.CharField(blank=True, db_index=True, max_length=15)),
                ('match_key', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=512)),
                ('primary_artist', models.CharField(max_length=512)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.TextField()),
                ('source_external_id', models.CharField(blank=True, max_length=255)),
                ('source_snapshot_id', models.CharField(blank=True, max_length=255)),
                ('track_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='completed', max_length=16)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist_imports', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='catalog.playlist')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to='catalog.source')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_key', models.CharField(max_length=512)),
                ('original_filename', models.CharField(blank=True, max_length=512)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('track', 'Track'), ('album', 'Album'), ('playlist', 'Playlist'), ('video', 'Video'), ('file', 'File')], max_length=16)),
                ('external_id', models.CharField(max_length=255)),
                ('url', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='catalog.playlist')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='catalog.source')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='catalog.track')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'external_id'], name='catalog_sou_source__f23bc4_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id', 'kind'), name='uniq_sourcelink_source_external_kind')],
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField()),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_playlist_tracks', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playlist_items', to='catalog.track')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('playlist', 'track'), name='uniq_playlisttrack_playlist_track')],
            },
        ),
        migrations.CreateModel(
            name='PlaybackSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locator_kind', models.CharField(choices=[('video_id', 'YouTube video id'), ('storage_key', 'Object-storage key'), ('url', 'Direct URL')], max_length=16)),
                ('locator', models.CharField(max_length=1024)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('uploader', models.CharField(blank=True, max_length=512)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('origin', models.CharField(choices=[('matched_auto', 'Matched (auto)'), ('matched_manual', 'Matched (manual correction)'), ('direct', 'Direct (paste/upload, no search)')], max_length=16)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('duration_delta_ms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('candidate', 'Candidate'), ('dead', 'Dead'), ('replaced', 'Replaced'), ('rejected', 'Rejected')], default='candidate', max_length=16)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_source_selections', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playback_sources', to='catalog.source')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_sources', to='catalog.track')),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_sources', to='catalog.upload')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['track', 'status'], name='catalog_pla_track_i_288c97_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('track',), name='one_active_playback_source_per_track')],
            },
        ),
    ]
