# Generated by Django 5.2.14 on 2026-06-03 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistimport',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='catalog.playlist'),
        ),
    ]
