# Generated by Django 5.2.14 on 2026-06-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_playlistimport_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album_name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='track',
            name='artwork_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='track',
            name='is_explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='preview_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
