# Generated by Django 5.2.14 on 2026-06-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_track_album_name_track_artwork_url_track_is_explicit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='source_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
