# Generated by Django 5.2.14 on 2026-06-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_track_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='artwork_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
