# Generated by Django 5.2.15 on 2026-06-05 01:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_playlist_artwork_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='origin_snapshot_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='SourcePlaylist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('owner_name', models.CharField(blank=True, max_length=512)),
                ('owner_url', models.URLField(blank=True, max_length=1024)),
                ('cover_url', models.URLField(blank=True, max_length=1024)),
                ('snapshot_id', models.CharField(blank=True, max_length=255)),
                ('track_count', models.IntegerField(default=0)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_playlists', to='catalog.source')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='catalog.sourceplaylist'),
        ),
        migrations.CreateModel(
            name='SourcePlaylistTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField()),
                ('source_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.sourceplaylist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_playlist_items', to='catalog.track')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='sourceplaylist',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_sourceplaylist_source_external'),
        ),
        migrations.AddConstraint(
            model_name='sourceplaylisttrack',
            constraint=models.UniqueConstraint(fields=('source_playlist', 'track'), name='uniq_sourceplaylisttrack_playlist_track'),
        ),
    ]
