# Generated by Django 5.2.14 on 2026-06-04 19:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_playlist_artwork_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refresh_token', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
