# Generated by Django 5.2.15 on 2026-06-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_playlist_origin_snapshot_id_sourceplaylist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceplaylist',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
