/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as PlaylistsPlaylistIdRouteImport } from './routes/playlists/$playlistId'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as AccountVerifyEmailRouteImport } from './routes/account/verify-email'
import { Route as AccountMfaRouteImport } from './routes/account/mfa'
import { Route as AccountEmailRouteImport } from './routes/account/email'
import { Route as AccountVerifyEmailIndexRouteImport } from './routes/account/verify-email/index'
import { Route as AccountMfaIndexRouteImport } from './routes/account/mfa/index'
import { Route as AccountVerifyEmailKeyRouteImport } from './routes/account/verify-email/$key'
import { Route as AccountPasswordForgotRouteImport } from './routes/account/password/forgot'
import { Route as AccountPasswordChangeRouteImport } from './routes/account/password/change'
import { Route as AccountMfaWebauthnRouteImport } from './routes/account/mfa/webauthn'
import { Route as AccountMfaTotpRouteImport } from './routes/account/mfa/totp'
import { Route as AccountMfaRecoveryCodesRouteImport } from './routes/account/mfa/recovery-codes'
import { Route as AccountPasswordResetKeyKeyRouteImport } from './routes/account/password/reset/key/$key'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const PlaylistsPlaylistIdRoute = PlaylistsPlaylistIdRouteImport.update({
  id: '/playlists/$playlistId',
  path: '/playlists/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const AccountVerifyEmailRoute = AccountVerifyEmailRouteImport.update({
  id: '/account/verify-email',
  path: '/account/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountMfaRoute = AccountMfaRouteImport.update({
  id: '/account/mfa',
  path: '/account/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountEmailRoute = AccountEmailRouteImport.update({
  id: '/account/email',
  path: '/account/email',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVerifyEmailIndexRoute = AccountVerifyEmailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountVerifyEmailRoute,
} as any)
const AccountMfaIndexRoute = AccountMfaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountMfaRoute,
} as any)
const AccountVerifyEmailKeyRoute = AccountVerifyEmailKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => AccountVerifyEmailRoute,
} as any)
const AccountPasswordForgotRoute = AccountPasswordForgotRouteImport.update({
  id: '/account/password/forgot',
  path: '/account/password/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPasswordChangeRoute = AccountPasswordChangeRouteImport.update({
  id: '/account/password/change',
  path: '/account/password/change',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountMfaWebauthnRoute = AccountMfaWebauthnRouteImport.update({
  id: '/webauthn',
  path: '/webauthn',
  getParentRoute: () => AccountMfaRoute,
} as any)
const AccountMfaTotpRoute = AccountMfaTotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => AccountMfaRoute,
} as any)
const AccountMfaRecoveryCodesRoute = AccountMfaRecoveryCodesRouteImport.update({
  id: '/recovery-codes',
  path: '/recovery-codes',
  getParentRoute: () => AccountMfaRoute,
} as any)
const AccountPasswordResetKeyKeyRoute =
  AccountPasswordResetKeyKeyRouteImport.update({
    id: '/account/password/reset/key/$key',
    path: '/account/password/reset/key/$key',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/account/email': typeof AccountEmailRoute
  '/account/mfa': typeof AccountMfaRouteWithChildren
  '/account/verify-email': typeof AccountVerifyEmailRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/docs/': typeof DocsIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/account/mfa/recovery-codes': typeof AccountMfaRecoveryCodesRoute
  '/account/mfa/totp': typeof AccountMfaTotpRoute
  '/account/mfa/webauthn': typeof AccountMfaWebauthnRoute
  '/account/password/change': typeof AccountPasswordChangeRoute
  '/account/password/forgot': typeof AccountPasswordForgotRoute
  '/account/verify-email/$key': typeof AccountVerifyEmailKeyRoute
  '/account/mfa/': typeof AccountMfaIndexRoute
  '/account/verify-email/': typeof AccountVerifyEmailIndexRoute
  '/account/password/reset/key/$key': typeof AccountPasswordResetKeyKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/account/email': typeof AccountEmailRoute
  '/docs/$': typeof DocsSplatRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/docs': typeof DocsIndexRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/account/mfa/recovery-codes': typeof AccountMfaRecoveryCodesRoute
  '/account/mfa/totp': typeof AccountMfaTotpRoute
  '/account/mfa/webauthn': typeof AccountMfaWebauthnRoute
  '/account/password/change': typeof AccountPasswordChangeRoute
  '/account/password/forgot': typeof AccountPasswordForgotRoute
  '/account/verify-email/$key': typeof AccountVerifyEmailKeyRoute
  '/account/mfa': typeof AccountMfaIndexRoute
  '/account/verify-email': typeof AccountVerifyEmailIndexRoute
  '/account/password/reset/key/$key': typeof AccountPasswordResetKeyKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/account/email': typeof AccountEmailRoute
  '/account/mfa': typeof AccountMfaRouteWithChildren
  '/account/verify-email': typeof AccountVerifyEmailRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/docs/': typeof DocsIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/account/mfa/recovery-codes': typeof AccountMfaRecoveryCodesRoute
  '/account/mfa/totp': typeof AccountMfaTotpRoute
  '/account/mfa/webauthn': typeof AccountMfaWebauthnRoute
  '/account/password/change': typeof AccountPasswordChangeRoute
  '/account/password/forgot': typeof AccountPasswordForgotRoute
  '/account/verify-email/$key': typeof AccountVerifyEmailKeyRoute
  '/account/mfa/': typeof AccountMfaIndexRoute
  '/account/verify-email/': typeof AccountVerifyEmailIndexRoute
  '/account/password/reset/key/$key': typeof AccountPasswordResetKeyKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/login'
    | '/notes'
    | '/settings'
    | '/signup'
    | '/account/email'
    | '/account/mfa'
    | '/account/verify-email'
    | '/docs/$'
    | '/playlists/$playlistId'
    | '/docs/'
    | '/playlists/'
    | '/account/mfa/recovery-codes'
    | '/account/mfa/totp'
    | '/account/mfa/webauthn'
    | '/account/password/change'
    | '/account/password/forgot'
    | '/account/verify-email/$key'
    | '/account/mfa/'
    | '/account/verify-email/'
    | '/account/password/reset/key/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notes'
    | '/settings'
    | '/signup'
    | '/account/email'
    | '/docs/$'
    | '/playlists/$playlistId'
    | '/docs'
    | '/playlists'
    | '/account/mfa/recovery-codes'
    | '/account/mfa/totp'
    | '/account/mfa/webauthn'
    | '/account/password/change'
    | '/account/password/forgot'
    | '/account/verify-email/$key'
    | '/account/mfa'
    | '/account/verify-email'
    | '/account/password/reset/key/$key'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/login'
    | '/notes'
    | '/settings'
    | '/signup'
    | '/account/email'
    | '/account/mfa'
    | '/account/verify-email'
    | '/docs/$'
    | '/playlists/$playlistId'
    | '/docs/'
    | '/playlists/'
    | '/account/mfa/recovery-codes'
    | '/account/mfa/totp'
    | '/account/mfa/webauthn'
    | '/account/password/change'
    | '/account/password/forgot'
    | '/account/verify-email/$key'
    | '/account/mfa/'
    | '/account/verify-email/'
    | '/account/password/reset/key/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  AccountEmailRoute: typeof AccountEmailRoute
  AccountMfaRoute: typeof AccountMfaRouteWithChildren
  AccountVerifyEmailRoute: typeof AccountVerifyEmailRouteWithChildren
  PlaylistsPlaylistIdRoute: typeof PlaylistsPlaylistIdRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  AccountPasswordChangeRoute: typeof AccountPasswordChangeRoute
  AccountPasswordForgotRoute: typeof AccountPasswordForgotRoute
  AccountPasswordResetKeyKeyRoute: typeof AccountPasswordResetKeyKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/playlists/$playlistId': {
      id: '/playlists/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof PlaylistsPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/account/verify-email': {
      id: '/account/verify-email'
      path: '/account/verify-email'
      fullPath: '/account/verify-email'
      preLoaderRoute: typeof AccountVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/mfa': {
      id: '/account/mfa'
      path: '/account/mfa'
      fullPath: '/account/mfa'
      preLoaderRoute: typeof AccountMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/email': {
      id: '/account/email'
      path: '/account/email'
      fullPath: '/account/email'
      preLoaderRoute: typeof AccountEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/verify-email/': {
      id: '/account/verify-email/'
      path: '/'
      fullPath: '/account/verify-email/'
      preLoaderRoute: typeof AccountVerifyEmailIndexRouteImport
      parentRoute: typeof AccountVerifyEmailRoute
    }
    '/account/mfa/': {
      id: '/account/mfa/'
      path: '/'
      fullPath: '/account/mfa/'
      preLoaderRoute: typeof AccountMfaIndexRouteImport
      parentRoute: typeof AccountMfaRoute
    }
    '/account/verify-email/$key': {
      id: '/account/verify-email/$key'
      path: '/$key'
      fullPath: '/account/verify-email/$key'
      preLoaderRoute: typeof AccountVerifyEmailKeyRouteImport
      parentRoute: typeof AccountVerifyEmailRoute
    }
    '/account/password/forgot': {
      id: '/account/password/forgot'
      path: '/account/password/forgot'
      fullPath: '/account/password/forgot'
      preLoaderRoute: typeof AccountPasswordForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/password/change': {
      id: '/account/password/change'
      path: '/account/password/change'
      fullPath: '/account/password/change'
      preLoaderRoute: typeof AccountPasswordChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/mfa/webauthn': {
      id: '/account/mfa/webauthn'
      path: '/webauthn'
      fullPath: '/account/mfa/webauthn'
      preLoaderRoute: typeof AccountMfaWebauthnRouteImport
      parentRoute: typeof AccountMfaRoute
    }
    '/account/mfa/totp': {
      id: '/account/mfa/totp'
      path: '/totp'
      fullPath: '/account/mfa/totp'
      preLoaderRoute: typeof AccountMfaTotpRouteImport
      parentRoute: typeof AccountMfaRoute
    }
    '/account/mfa/recovery-codes': {
      id: '/account/mfa/recovery-codes'
      path: '/recovery-codes'
      fullPath: '/account/mfa/recovery-codes'
      preLoaderRoute: typeof AccountMfaRecoveryCodesRouteImport
      parentRoute: typeof AccountMfaRoute
    }
    '/account/password/reset/key/$key': {
      id: '/account/password/reset/key/$key'
      path: '/account/password/reset/key/$key'
      fullPath: '/account/password/reset/key/$key'
      preLoaderRoute: typeof AccountPasswordResetKeyKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface AccountMfaRouteChildren {
  AccountMfaRecoveryCodesRoute: typeof AccountMfaRecoveryCodesRoute
  AccountMfaTotpRoute: typeof AccountMfaTotpRoute
  AccountMfaWebauthnRoute: typeof AccountMfaWebauthnRoute
  AccountMfaIndexRoute: typeof AccountMfaIndexRoute
}

const AccountMfaRouteChildren: AccountMfaRouteChildren = {
  AccountMfaRecoveryCodesRoute: AccountMfaRecoveryCodesRoute,
  AccountMfaTotpRoute: AccountMfaTotpRoute,
  AccountMfaWebauthnRoute: AccountMfaWebauthnRoute,
  AccountMfaIndexRoute: AccountMfaIndexRoute,
}

const AccountMfaRouteWithChildren = AccountMfaRoute._addFileChildren(
  AccountMfaRouteChildren,
)

interface AccountVerifyEmailRouteChildren {
  AccountVerifyEmailKeyRoute: typeof AccountVerifyEmailKeyRoute
  AccountVerifyEmailIndexRoute: typeof AccountVerifyEmailIndexRoute
}

const AccountVerifyEmailRouteChildren: AccountVerifyEmailRouteChildren = {
  AccountVerifyEmailKeyRoute: AccountVerifyEmailKeyRoute,
  AccountVerifyEmailIndexRoute: AccountVerifyEmailIndexRoute,
}

const AccountVerifyEmailRouteWithChildren =
  AccountVerifyEmailRoute._addFileChildren(AccountVerifyEmailRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  AccountEmailRoute: AccountEmailRoute,
  AccountMfaRoute: AccountMfaRouteWithChildren,
  AccountVerifyEmailRoute: AccountVerifyEmailRouteWithChildren,
  PlaylistsPlaylistIdRoute: PlaylistsPlaylistIdRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  AccountPasswordChangeRoute: AccountPasswordChangeRoute,
  AccountPasswordForgotRoute: AccountPasswordForgotRoute,
  AccountPasswordResetKeyKeyRoute: AccountPasswordResetKeyKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
