/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountVerifyEmailRouteImport } from './routes/account/verify-email'
import { Route as AccountMfaRouteImport } from './routes/account/mfa'
import { Route as AccountVerifyEmailKeyRouteImport } from './routes/account/verify-email/$key'
import { Route as AccountPasswordForgotRouteImport } from './routes/account/password/forgot'
import { Route as AccountMfaWebauthnRouteImport } from './routes/account/mfa/webauthn'
import { Route as AccountMfaTotpRouteImport } from './routes/account/mfa/totp'
import { Route as AccountMfaRecoveryCodesRouteImport } from './routes/account/mfa/recovery-codes'
import { Route as AccountPasswordResetKeyKeyRouteImport } from './routes/account/password/reset/key/$key'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVerifyEmailRoute = AccountVerifyEmailRouteImport.update({
  id: '/account/verify-email',
  path: '/account/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountMfaRoute = AccountMfaRouteImport.update({
  id: '/account/mfa',
  path: '/account/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVerifyEmailKeyRoute = AccountVerifyEmailKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => AccountVerifyEmailRoute,
} as any)
const AccountPasswordForgotRoute = AccountPasswordForgotRouteImport.update({
  id: '/account/password/forgot',
  path: '/account/password/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountMfaWebauthnRoute = AccountMfaWebauthnRouteImport.update({
  id: '/webauthn',
  path: '/webauthn',
  getParentRoute: () => AccountMfaRoute,
} as any)
const AccountMfaTotpRoute = AccountMfaTotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => AccountMfaRoute,
} as any)
const AccountMfaRecoveryCodesRoute = AccountMfaRecoveryCodesRouteImport.update({
  id: '/recovery-codes',
  path: '/recovery-codes',
  getParentRoute: () => AccountMfaRoute,
} as any)
const AccountPasswordResetKeyKeyRoute =
  AccountPasswordResetKeyKeyRouteImport.update({
    id: '/account/password/reset/key/$key',
    path: '/account/password/reset/key/$key',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/account/mfa': typeof AccountMfaRouteWithChildren
  '/account/verify-email': typeof AccountVerifyEmailRouteWithChildren
  '/account/mfa/recovery-codes': typeof AccountMfaRecoveryCodesRoute
  '/account/mfa/totp': typeof AccountMfaTotpRoute
  '/account/mfa/webauthn': typeof AccountMfaWebauthnRoute
  '/account/password/forgot': typeof AccountPasswordForgotRoute
  '/account/verify-email/$key': typeof AccountVerifyEmailKeyRoute
  '/account/password/reset/key/$key': typeof AccountPasswordResetKeyKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/account/mfa': typeof AccountMfaRouteWithChildren
  '/account/verify-email': typeof AccountVerifyEmailRouteWithChildren
  '/account/mfa/recovery-codes': typeof AccountMfaRecoveryCodesRoute
  '/account/mfa/totp': typeof AccountMfaTotpRoute
  '/account/mfa/webauthn': typeof AccountMfaWebauthnRoute
  '/account/password/forgot': typeof AccountPasswordForgotRoute
  '/account/verify-email/$key': typeof AccountVerifyEmailKeyRoute
  '/account/password/reset/key/$key': typeof AccountPasswordResetKeyKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/account/mfa': typeof AccountMfaRouteWithChildren
  '/account/verify-email': typeof AccountVerifyEmailRouteWithChildren
  '/account/mfa/recovery-codes': typeof AccountMfaRecoveryCodesRoute
  '/account/mfa/totp': typeof AccountMfaTotpRoute
  '/account/mfa/webauthn': typeof AccountMfaWebauthnRoute
  '/account/password/forgot': typeof AccountPasswordForgotRoute
  '/account/verify-email/$key': typeof AccountVerifyEmailKeyRoute
  '/account/password/reset/key/$key': typeof AccountPasswordResetKeyKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notes'
    | '/settings'
    | '/signup'
    | '/account/mfa'
    | '/account/verify-email'
    | '/account/mfa/recovery-codes'
    | '/account/mfa/totp'
    | '/account/mfa/webauthn'
    | '/account/password/forgot'
    | '/account/verify-email/$key'
    | '/account/password/reset/key/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notes'
    | '/settings'
    | '/signup'
    | '/account/mfa'
    | '/account/verify-email'
    | '/account/mfa/recovery-codes'
    | '/account/mfa/totp'
    | '/account/mfa/webauthn'
    | '/account/password/forgot'
    | '/account/verify-email/$key'
    | '/account/password/reset/key/$key'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/notes'
    | '/settings'
    | '/signup'
    | '/account/mfa'
    | '/account/verify-email'
    | '/account/mfa/recovery-codes'
    | '/account/mfa/totp'
    | '/account/mfa/webauthn'
    | '/account/password/forgot'
    | '/account/verify-email/$key'
    | '/account/password/reset/key/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  AccountMfaRoute: typeof AccountMfaRouteWithChildren
  AccountVerifyEmailRoute: typeof AccountVerifyEmailRouteWithChildren
  AccountPasswordForgotRoute: typeof AccountPasswordForgotRoute
  AccountPasswordResetKeyKeyRoute: typeof AccountPasswordResetKeyKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/verify-email': {
      id: '/account/verify-email'
      path: '/account/verify-email'
      fullPath: '/account/verify-email'
      preLoaderRoute: typeof AccountVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/mfa': {
      id: '/account/mfa'
      path: '/account/mfa'
      fullPath: '/account/mfa'
      preLoaderRoute: typeof AccountMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/verify-email/$key': {
      id: '/account/verify-email/$key'
      path: '/$key'
      fullPath: '/account/verify-email/$key'
      preLoaderRoute: typeof AccountVerifyEmailKeyRouteImport
      parentRoute: typeof AccountVerifyEmailRoute
    }
    '/account/password/forgot': {
      id: '/account/password/forgot'
      path: '/account/password/forgot'
      fullPath: '/account/password/forgot'
      preLoaderRoute: typeof AccountPasswordForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/mfa/webauthn': {
      id: '/account/mfa/webauthn'
      path: '/webauthn'
      fullPath: '/account/mfa/webauthn'
      preLoaderRoute: typeof AccountMfaWebauthnRouteImport
      parentRoute: typeof AccountMfaRoute
    }
    '/account/mfa/totp': {
      id: '/account/mfa/totp'
      path: '/totp'
      fullPath: '/account/mfa/totp'
      preLoaderRoute: typeof AccountMfaTotpRouteImport
      parentRoute: typeof AccountMfaRoute
    }
    '/account/mfa/recovery-codes': {
      id: '/account/mfa/recovery-codes'
      path: '/recovery-codes'
      fullPath: '/account/mfa/recovery-codes'
      preLoaderRoute: typeof AccountMfaRecoveryCodesRouteImport
      parentRoute: typeof AccountMfaRoute
    }
    '/account/password/reset/key/$key': {
      id: '/account/password/reset/key/$key'
      path: '/account/password/reset/key/$key'
      fullPath: '/account/password/reset/key/$key'
      preLoaderRoute: typeof AccountPasswordResetKeyKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountMfaRouteChildren {
  AccountMfaRecoveryCodesRoute: typeof AccountMfaRecoveryCodesRoute
  AccountMfaTotpRoute: typeof AccountMfaTotpRoute
  AccountMfaWebauthnRoute: typeof AccountMfaWebauthnRoute
}

const AccountMfaRouteChildren: AccountMfaRouteChildren = {
  AccountMfaRecoveryCodesRoute: AccountMfaRecoveryCodesRoute,
  AccountMfaTotpRoute: AccountMfaTotpRoute,
  AccountMfaWebauthnRoute: AccountMfaWebauthnRoute,
}

const AccountMfaRouteWithChildren = AccountMfaRoute._addFileChildren(
  AccountMfaRouteChildren,
)

interface AccountVerifyEmailRouteChildren {
  AccountVerifyEmailKeyRoute: typeof AccountVerifyEmailKeyRoute
}

const AccountVerifyEmailRouteChildren: AccountVerifyEmailRouteChildren = {
  AccountVerifyEmailKeyRoute: AccountVerifyEmailKeyRoute,
}

const AccountVerifyEmailRouteWithChildren =
  AccountVerifyEmailRoute._addFileChildren(AccountVerifyEmailRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  AccountMfaRoute: AccountMfaRouteWithChildren,
  AccountVerifyEmailRoute: AccountVerifyEmailRouteWithChildren,
  AccountPasswordForgotRoute: AccountPasswordForgotRoute,
  AccountPasswordResetKeyKeyRoute: AccountPasswordResetKeyKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
