/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Account2faRouteImport } from './routes/account/2fa'
import { Route as Account2faWebauthnRouteImport } from './routes/account/2fa/webauthn'
import { Route as Account2faTotpRouteImport } from './routes/account/2fa/totp'
import { Route as Account2faRecoveryCodesRouteImport } from './routes/account/2fa/recovery-codes'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Account2faRoute = Account2faRouteImport.update({
  id: '/account/2fa',
  path: '/account/2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const Account2faWebauthnRoute = Account2faWebauthnRouteImport.update({
  id: '/webauthn',
  path: '/webauthn',
  getParentRoute: () => Account2faRoute,
} as any)
const Account2faTotpRoute = Account2faTotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => Account2faRoute,
} as any)
const Account2faRecoveryCodesRoute = Account2faRecoveryCodesRouteImport.update({
  id: '/recovery-codes',
  path: '/recovery-codes',
  getParentRoute: () => Account2faRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/account/2fa': typeof Account2faRouteWithChildren
  '/account/2fa/recovery-codes': typeof Account2faRecoveryCodesRoute
  '/account/2fa/totp': typeof Account2faTotpRoute
  '/account/2fa/webauthn': typeof Account2faWebauthnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/account/2fa': typeof Account2faRouteWithChildren
  '/account/2fa/recovery-codes': typeof Account2faRecoveryCodesRoute
  '/account/2fa/totp': typeof Account2faTotpRoute
  '/account/2fa/webauthn': typeof Account2faWebauthnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/account/2fa': typeof Account2faRouteWithChildren
  '/account/2fa/recovery-codes': typeof Account2faRecoveryCodesRoute
  '/account/2fa/totp': typeof Account2faTotpRoute
  '/account/2fa/webauthn': typeof Account2faWebauthnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notes'
    | '/settings'
    | '/signup'
    | '/account/2fa'
    | '/account/2fa/recovery-codes'
    | '/account/2fa/totp'
    | '/account/2fa/webauthn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notes'
    | '/settings'
    | '/signup'
    | '/account/2fa'
    | '/account/2fa/recovery-codes'
    | '/account/2fa/totp'
    | '/account/2fa/webauthn'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/notes'
    | '/settings'
    | '/signup'
    | '/account/2fa'
    | '/account/2fa/recovery-codes'
    | '/account/2fa/totp'
    | '/account/2fa/webauthn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  Account2faRoute: typeof Account2faRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/2fa': {
      id: '/account/2fa'
      path: '/account/2fa'
      fullPath: '/account/2fa'
      preLoaderRoute: typeof Account2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/2fa/webauthn': {
      id: '/account/2fa/webauthn'
      path: '/webauthn'
      fullPath: '/account/2fa/webauthn'
      preLoaderRoute: typeof Account2faWebauthnRouteImport
      parentRoute: typeof Account2faRoute
    }
    '/account/2fa/totp': {
      id: '/account/2fa/totp'
      path: '/totp'
      fullPath: '/account/2fa/totp'
      preLoaderRoute: typeof Account2faTotpRouteImport
      parentRoute: typeof Account2faRoute
    }
    '/account/2fa/recovery-codes': {
      id: '/account/2fa/recovery-codes'
      path: '/recovery-codes'
      fullPath: '/account/2fa/recovery-codes'
      preLoaderRoute: typeof Account2faRecoveryCodesRouteImport
      parentRoute: typeof Account2faRoute
    }
  }
}

interface Account2faRouteChildren {
  Account2faRecoveryCodesRoute: typeof Account2faRecoveryCodesRoute
  Account2faTotpRoute: typeof Account2faTotpRoute
  Account2faWebauthnRoute: typeof Account2faWebauthnRoute
}

const Account2faRouteChildren: Account2faRouteChildren = {
  Account2faRecoveryCodesRoute: Account2faRecoveryCodesRoute,
  Account2faTotpRoute: Account2faTotpRoute,
  Account2faWebauthnRoute: Account2faWebauthnRoute,
}

const Account2faRouteWithChildren = Account2faRoute._addFileChildren(
  Account2faRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  Account2faRoute: Account2faRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
